pipeline:
  scp:
    image: appleboy/drone-scp
    host: 
      - 54.199.220.164
    port: 22
    username: ec2-user
    secrets: 
      - source: password
        target: scp_password
    rm: true
    target: /home/ec2-user/data/drone-demo
    source: 
      - "*.js"
      - "*.json"
    when:
      branch: master
      local: true
    