pipeline:
  install:
    image: node:10.15
    commands:
      - node -v
      - npm -v
      - npm install
      - npm install -g mocha
      - mocha test/api.js

  scp:
    image: appleboy/drone-scp
    host: 
      - 13.230.240.54
    port: 22
    secrets:
      - source: user_name
        target: scp_username
      - source: key2
        target: scp_key
    rm: true
    target: /home/ec2-user/data/drone-demo
    source: 
      - "*.*"
      - "test/*.*"
      - "node_modules"
      #- "*.js"
      #- "*.json"
      #- "test/*.json"
    when:
      branch: master
      local: true

  ssh:
    image: appleboy/drone-ssh
    host: 13.230.240.54
    username: ec2-user
    secrets: 
      - source: key2
        target: ssh_key
    script:
      - cd /home/ec2-user/data/drone-demo
      #- echo "install forever ..."
      #- npm install -g forever
      - echo "kill running service ..."
      - forever stop 0
      - echo "start service..."
      - forever start index.js
      - exit 0
    when:
      branch: master
      local: true

  notify: 
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: gomaji_shell
    username: Drone CI
    when:
      status: [ success, failure ]