pipeline:
  install:
    image: node:10.15
    commands:
      - node -v
      - npm -v
      - npm install
      - npm install -g mocha
      - mocha test/api.js

  scp:
    image: appleboy/drone-scp
    host: 
      - 13.230.240.54
    port: 22
    secrets:
      - source: user_name
        target: scp_username
      - source: key_path
        target: scp_key_path
    rm: true
    target: /home/ec2-user/data/drone-demo
    source: 
      - "*.*"
      - "test/*.*"
      - "node_modules"
      #- "*.js"
      #- "*.json"
      #- "test/*.json"
    when:
      branch: master
      local: true

  run:
    image: appleboy/drone-ssh
    host: 52.197.108.200
    username: ec2-user
    secrets: 
      - source: password
        target: ssh_password
    script:
      - pwd
      - cd /home/ec2-user/data/drone-demo
      - pwd
      - echo "start service..."
      - node index.js
    