pipeline:
  install:
    image: node:10.15
    commands:
      - node -v
      - npm -v
      - npm install
      - npm install -g mocha
      - mocha test/api.js
    when:
      branch: docker

  build_image:
    image: plugins/docker
    pull: true
    repo: liu71101/drone-demo
    tags: [ latest, 1.0 ]
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ] 
    when:
      branch: docker

  notify:
    image: plugins/slack
    channel: gomaji_shell
    secrets: [ slack_webhook ]
    username: Drone CI
    when:
      status: [ success, failure ]