pipeline:
  scp:
    image: appleboy/drone-scp
    host: 
      - 52.197.108.200
    port: 22
    #username: ec2-user
    secrets: 
      - source: password
        target: scp_password
      - source: username
        target: scp_username
    rm: true
    target: /home/ec2-user/data/drone-demo
    source: 
      - "*.js"
      - "*.json"
    when:
      branch: master
      local: true
    